### ISSUE TITLE
Uso de system

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_2122-codehub#10]
La función `system` permite ejecutar comandos del sistema operativo. Por tanto, su inclusión dentro del código implica que éste no es portable (es decir, únicamente se puede compilar y ejecutar en un sistema operativo). Debéis eliminar su uso y sustituirlo por otras opciones (mirad el punto 3 de [este documento](https://github.com/oscarperpinan/informatica_etsidi/raw/master/ejercicios/misc.pdf)).
https://github.com/aigora/twE105_2122-codehub/blob/9e02610d89867c80c88c32a3cb1338aa275e4f8f/main.c#L56

**Comment by bforteza** [comment]
Buenas, gracias por el comentario, pero este archivo se trataba de funciones iniciales y de pruebas, ahora lo eliminamos
