### ISSUE TITLE
Desarrollo de las principales funciones

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_2122-codehub#3]
Debéis implementar las principales funciones del programa.
Esta implementación puede tener cambios en la versión definitiva. Aún no es necesario que realice todas las funcionalidades previstas.
Se recomienda el uso de librerías propias para alojar estas funciones.

**Comment by bforteza** [comment]
este issue ha sido cerrado demasiado tarde realmente, ya que desde el inicio se implementaron las primeras funciones, pero al 
no estar configurado el menú podria resultar un poco extraño cerrarlo entonces
