### ISSUE TITLE
Definición de las estructuras

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_2122-codehub#4]
Debéis implementar la definición de las principales estructuras (datos tipo `struct`) que se usan en el programa.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by bforteza** [comment]
la principal y una estructura de nuestro programa es la estructura casilla, aunque solo tengamos una estructura esta se encuentra muy presente dentro del juego, tanto en la generación de mapa como en la parte mas grafica.
